version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    command: sh ./compose/entrypoint.sh
    volumes:
      - .:/sunserver
    ports:
      - "8000:8000"
    environment:
      MODE_ENVIROMENT: dev
      N2YO_API_KEY: ${N2YO_API_KEY}
      MQTT_HOST: ${MQTT_HOST}
