# Generated by Django 2.1.2 on 2018-11-12 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tle',
            fields=[
                ('norad', models.IntegerField(primary_key=True, serialize=False)),
                ('line1', models.CharField(max_length=69)),
                ('line2', models.CharField(max_length=69)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
