# Generated by Django 2.1.2 on 2018-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armposition',
            name='engine_speed',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
