# Generated by Django 2.1.2 on 2018-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_armdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armposition',
            name='engine_speed',
        ),
        migrations.RemoveField(
            model_name='armposition',
            name='magnetometer',
        ),
        migrations.AddField(
            model_name='armdata',
            name='engine_speed',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='armdata',
            name='magnetometer',
            field=models.FloatField(default=0.0),
        ),
    ]
